// Generates app/lib/manual.generated.ts from docs/manual/**/*.md at build time.
// Runs in `predev`/`prebuild` (and `pnpm gen:manual`). This keeps the manual out
// of the request-time filesystem entirely — the app imports plain data, so it
// works identically locally and on Vercel (no output-file-tracing needed).
import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { join, relative, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { marked } from "marked";

const APP_DIR = join(dirname(fileURLToPath(import.meta.url)), "..");
const MANUAL_DIR = join(APP_DIR, "..", "docs", "manual");
const OUT = join(APP_DIR, "lib", "manual.generated.ts");

function walk(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) out.push(...walk(full));
    else if (name.endsWith(".md")) out.push(full);
  }
  return out;
}

// Our front-matter is a flat block of `key: value` and `key: [a, b]` — parse it
// directly rather than pulling in a YAML dependency.
function parseFrontMatter(raw) {
  const match = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!match) return { data: {}, body: raw };
  const data = {};
  for (const line of match[1].split(/\r?\n/)) {
    const m = line.match(/^([A-Za-z0-9_]+):\s*(.*)$/);
    if (!m) continue;
    let [, key, value] = m;
    value = value.trim();
    if (value.startsWith("[") && value.endsWith("]")) {
      data[key] = value
        .slice(1, -1)
        .split(",")
        .map((s) => s.trim().replace(/^["']|["']$/g, ""))
        .filter(Boolean);
    } else {
      data[key] = value.replace(/^["']|["']$/g, "");
    }
  }
  return { data, body: match[2] };
}

// Turn relative .md cross-links into in-app /help links (resolved against the
// page's own folder); leave external and non-.md links untouched.
function rewriteLinks(html, slug) {
  const dir = slug.includes("/") ? slug.slice(0, slug.lastIndexOf("/")) : "";
  return html.replace(/href="([^"]+)"/g, (full, href) => {
    if (/^(https?:|mailto:|#|\/help\/)/.test(href) || !/\.md(#|$)/.test(href)) return full;
    const [path, anchor] = href.split("#");
    const target = join(dir, path).replace(/\\/g, "/").replace(/\.md$/, "").replace(/\/README$/, "");
    if (target.startsWith("..")) return full; // link escapes the manual — leave it
    return `href="/help/${target}${anchor ? "#" + anchor : ""}"`;
  });
}

const entries = walk(MANUAL_DIR)
  .map((file) => {
    const { data, body } = parseFrontMatter(readFileSync(file, "utf8"));
    const rel = relative(MANUAL_DIR, file).replace(/\\/g, "/");
    const slug = rel.replace(/\.md$/, "").replace(/\/README$/, "").replace(/^README$/, "index");
    const section = slug.includes("/") ? slug.split("/")[0] : "general";
    return {
      slug,
      title: data.title ?? slug,
      section,
      audience: Array.isArray(data.audience) ? data.audience : [],
      module: data.module ?? null,
      feature: data.feature ?? null,
      path: data.path ?? null,
      status: data.status ?? "planned",
      updated: data.updated ?? null,
      html: rewriteLinks(marked.parse(body.trim(), { async: false }), slug),
    };
  })
  .sort((a, b) => a.slug.localeCompare(b.slug));

const banner =
  "// AUTO-GENERATED by scripts/build-manual.mjs — do not edit. Run `pnpm gen:manual`.\n";
writeFileSync(
  OUT,
  `${banner}import type { ManualEntry } from "./manual";\n\nexport const MANUAL: ManualEntry[] = ${JSON.stringify(entries, null, 2)};\n`
);
console.log(`manual: generated ${entries.length} entries -> ${relative(APP_DIR, OUT)}`);
